### ISSUE TITLE
Venus "Settings > Enery meters" is empty and 3rd party script don't read AC Loads

### ISSUE THREAD

**Issue by Head** [mr-manuel/venus-os_dbus-mqtt-grid#1]
Hi,

I have this script running and it looks like it's working as expected. On the home screen I see Grid and AC Loads with correct values.

Once I go into the Venus Settings and scroll down to "Energy meters" it's empty. Is this a problem?

I'm now trying to combine my Venus OS with https://github.com/Telekatz/venus.dbus-hoymiles and this script has a "Setup > Power Meters" section which says "Unknown". Sounds similar to the "Enery meters" in the Venus Settings? It seem to read from `com.victronenergy.acload` https://github.com/Telekatz/venus.dbus-hoymiles/blob/89568b623ee798afa108b93a317de1868b239a1f/HMpvinverter.py#L1162 ?

Do you know if `venus.dbus-hoymiles` is reading it wrong or do you miss something while publishing the AC loads?

**Comment by mr-manuel** [comment]
Hello,

it is normal that the Energy Meter is empty, since this is a grid meter. Since this driver is intended to be a grid meter and not energy meter it‘s not pushing the data to `com.victronenergy.acload`. I also didn‘t find documentation about this in the dbus wiki https://github.com/victronenergy/venus/wiki/dbus

I will take a look in the next days.
